server:
  port: 8081


mybatis:
  type-aliases-package: com.lierlin.pojo.User
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloud-provider-hystrix-8081
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tt?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot


eureka:
  client:
      service-url:
        defaultZone: http://localhost:8082/eureka/
  instance:
    instance-id: springcloud-provider-8081
info:
  app.name: lierlin-springcloud
  company.nam: lierlin.company.com
